### PR TITLE
pkg: Add author and change SX127x prefix

### PR DESCRIPTION
**Pull request by jia200x**
Hi Alex,

I'm pushing 2 commits to your branch:

1. Add @fjmolinas to authors (in files we worked on at Inria Chile). As seen [here] in the commits, we coworked the initial adoption.
2. Change SX1276 prefixes to SX127x.

Cheers

[here]:https://github.com/Inria-Chile/RIOT/tree/LoRaMAC_port

### CODE REVIEW

**Comment by aabadie** [comment]
Please rework the PR, you are confusing me

**Comment by aabadie** [comment]
Better commenting in the initial PR where Francisco credit is missing, I'll add him

**Comment by jia200x** [comment]
yes, sorry. Thought it was easier here.
Thanks

**Comment by aabadie** [comment]
Thanks for reviewing btw @jia200x !

**Pull request closed without merging**
