### PR TITLE
boards/nucleo-f091: add i2c config

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

Add config for stm32f091 and nucleo-f091

### CODE REVIEW

**Comment by aabadie** [comment]
Thanks, but to minimize the final size of this PR, I wanted to do this once the new I2C interface feature branch is merged. Is it ok ?
But I guess you could also make it work on this board :)

**Comment by vincent-d** [comment]
I don't mind, I needed this to test on one of the f0 I have ;)

I'll rebase this once everything is merged.

**Comment by aabadie** [comment]
I should have configured this one, since I also have it. But finally went for the f070...

**Comment by aabadie** [comment]
@vincent-d, now that I2C refactoring is in, you can rebase and PR this upstream. I have the hardware for testing :)

**Comment by vincent-d** [comment]
see https://github.com/RIOT-OS/RIOT/pull/9727

**Pull request closed without merging**
